include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
      inference_failure_on_untyped_parameter: ignore
  plugins:
    - dart_code_metrics
  exclude:
    - lib/firebase_options.dart
    - lib/const/l10n/**
    - "**.freezed.dart"
    - "**.config.dart"
    - "**.gen.dart"
    - "**.g.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
    

dart_code_metrics:
  rules:
    - always-remove-listener
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - avoid-dynamic
    - binary-expression-operand-order
    - no-equal-then-else
    - prefer-trailing-comma
    - member-ordering:
        alphabetize: false # TODO set true after code-dart_code_metrics update
        order:
          - public-fields
          - public-getters
          - public-setters
          - private-fields
          - private-getters
          - private-setters
          - constructors
          - public-methods
          - private-methods
          
        
linter:
  rules:
    constant_identifier_names: false
    one_member_abstracts: false
    # Error rules.
    always_use_package_imports: true
    avoid_dynamic_calls: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    unsafe_html: true

    # Style rules.
    always_declare_return_types: true
    avoid_annotating_with_dynamic: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_escaping_inner_quotes: true
    avoid_field_initializers_in_const_classes: true
    avoid_implementing_value_types: true
    avoid_js_rounded_ints: true
    avoid_multiple_declarations_per_line: true
    avoid_positional_boolean_parameters: true
    avoid_private_typedef_functions: true
    avoid_redundant_argument_values: true
    avoid_returning_null: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    avoid_types_on_closure_parameters: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cascade_invocations: true
    deprecated_consistency: true
    directives_ordering: true
    do_not_use_environment: true
    leading_newlines_in_multiline_strings: true
    missing_whitespace_between_adjacent_strings: true
    no_runtimeType_toString: true
    omit_local_variable_types: true
    only_throw_errors: true
    package_api_docs: true
    parameter_assignments: true
    prefer_asserts_in_initializer_lists: true
    prefer_constructors_over_static_methods: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_mixin: true
    prefer_single_quotes: true
    type_annotate_public_apis: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_null_checks: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_raw_strings: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_to_and_as_if_applicable: true
    lines_longer_than_80_chars: false
    flutter_style_todos: false
    conditional_uri_does_not_exist: true
    secure_pubspec_urls: true
    sized_box_shrink_expand: true
    use_decorated_box: true
    use_colored_box: true

    # Pub rules.
    package_names: true
